# fly.toml app configuration file generated for pipe-client on 2023-07-20T18:08:20+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pipe-client"
primary_region = "iad"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ["app"]


[build]
  dockerfile = "Dockerfile"

[env]
  ENDPOINT = "https://pipe-server.fly.dev"
  ENDPOINT_TOKEN = "TOKEN"
  CLIENT_NAME="flying pipe"
