[package]
name = "mycelite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
section = { path = "../../" }
## FIXME: re-export through section?
futures = "0.3"
arrow = { version = "42", features = ["prettyprint"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
notify = { version = "6", default-features = false, features = ["macos_kqueue"] }
journal = { git = "https://github.com/mycelial/mycelite", rev="fd1d472eea7e359772e55fff05a73361a349e958", features=["async"] }
