[package]
name = "sqlite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
section = { path = "../../" }
sqlite3-parser = "0.9"
fallible-iterator = "0.3.0"
sqlx = { version = "0.7", features = ["sqlite"] }
notify = { version = "6", default-features = false, features = ["macos_kqueue"] }
futures = "0.3"
tokio = { version = "1", features=["full"] }
tokio-stream = "0.1"
thiserror = "1"

[dev-dependencies]
tempfile = "3.8"
stub = { path = "../stub/" }
section = { path = "../../", features=["dummy"] }
tokio-util = "0.7"
