[package]
name = "inspect"
version = "0.1.0"
edition = "2021"

[features]
default = ["section"]
section = []

[dependencies]
section = { path = "../../section" }
tracing = "0.1"
config = { path = "../../config" }