[profile.dev]
debug = true
opt-level = "s"
strip = true

[profile.release]
debug = true
opt-level = "s"
lto = true
codegen-units = 1
strip = true
incremental = false

[build]
rustflags = ["--cfg=web_sys_unstable_apis"]