[package]
name = "redshift_loader"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio", "runtime-tokio-native-tls", "rust_decimal", "chrono", "uuid"] }
section = { path = "../../../section/" }
chrono = "0.4"
log = "0.4"
tracing = "0.1"

[dev-dependencies]
stub = { path = "../stub" }
clap = { version = "4", features=["derive", "env"] }
tokio-util = "0.7"
tokio-stream = "0.1"
tracing-subscriber = "0.3"