[package]
name = "ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.5", features = ["web", "router"] }
futures = "0.3"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
web-sys = { version = "0.3", features = ["Window"] }
config = { path = "../config" }
dioxus-logger = "0.5.1"

[dev-dependencies]
quickcheck = "1.0.3"
