[package]
name = "ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.5", features = ["web", "router"] }
#dioxus-sdk = { git = "https://github.com/DioxusLabs/sdk", rev = "57ab3fa", features=["use_window_size"]}
futures = "0.3"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-wasm = "0.2"
web-sys = { version = "0.3.69", features = ["Window"] }